# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RedPager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RedPager
pod ‘Firebase/Messaging’

end
